name: Deploy Keycloak

on:
  push:
    branches:
      - deploy-keycloak

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/ssre_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ssre_rsa
          chmod 600 ~/.ssh/ssre_rsa
          ssh-keyscan -H ssh.freedomwalking.net >> ~/.ssh/known_hosts

      - name: Deploy to Ubuntu Server
        run: |
          ssh -i ~/.ssh/ssre_rsa -T -o StrictHostKeyChecking=no ssre@ssh.freedomwalking.net << 'EOF'
          set -e  # Dừng nếu có lỗi
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          TODAY=$(date +%Y%m%d)

          echo "🔹 Tạo namespace tránh trùng lặp..."
          kubectl create namespace keycloak-\$TODAY || true

          echo "🔹 Thay thế biến TODAY trong YAML..."
          export TODAY=\$TODAY

          echo "🔹 Đang deploy Postgres..."
          kubectl apply -f postgres.yaml

          echo "🔹 Đang deploy Keycloak..."
          kubectl apply -f keycloak.yaml

          echo "🔹 Đang deploy Keycloak Service..."
          kubectl apply -f keycloak-service.yaml

          echo "✅ Deploy hoàn tất!"
          EOF
